### ISSUE TITLE
[Crash] Latest connected glass version crashing

### ISSUE THREAD

**Issue by Sakatsuky** [SuperMartijn642/ConnectedGlass#32]
**Version Info**
- Minecraft, 1.19.2
- SuperMartijn642's CoreLib, 1.1.0
- Connected Glass, 1.1.5
- Forge, 43.2.3

**Crash report (~/logs/latest.log)**
[latest.zip](https://github.com/SuperMartijn642/ConnectedGlass/files/10333584/latest.zip)

**Comment by agentwolf88** [comment]
same

**Comment by Sakatsuky** [comment]
probably it's the forge version i think

**Comment by OGNymbil** [comment]
Same issue. I just downloaded and installed today with forge 43.1.7 and 43.2.0 it just crashes with an innovationtargetexception error. Going to try removing optifine and my shaders and try again, but will choose shaders over this mod if they won't work together.

**Comment by Sakatsuky** [comment]
I dont't use optfine/rubidium or shaders and it crashes.

**Comment by OGNymbil** [comment]
Yeah, I removed everything but this mod, and tried several versions of forge, and got nothing but crashes.

**Comment by SuperMartijn642** [comment]
It was crashing because tried to load a class from Rechiseled. I fixed it now in version 1.0.6 of Connected Glass.

Thank you for reporting the issue!

**Comment by brisingraerowing** [comment]
1.1.6 is still crashing on 1.12.2 with the exact same log.

[Crash Log](https://gist.github.com/brisingraerowing/f37aee7913d2ac5d1c3553705ce59593)

**Comment by SuperMartijn642** [comment]
@brisingraerowing Fixed now in 1.1.6a for Minecraft 1.12. No clue why everything needs to be weirdly stupid in 1.12.
